### ISSUE TITLE
Try your c# example with AF 

### ISSUE THREAD

**Issue by vovikdrg** [mailjet/mailjet-apiv3-dotnet#11]
I have an issue i pulled your library and added your example but I am getting an error 

System.MissingMethodException: 'Method not found: 'Mailjet.Client.MailjetRequest Mailjet.Client.MailjetRequest.Property(System.String, Newtonsoft.Json.Linq.JToken)'.'

**Comment by kmanchikov** [comment]
Hi,

We would be happy to have a closer look and get to the root cause of the issue, but first I would have to redirect you to our support channel here ( https://app.mailjet.com/support/ticket ) were you could open a ticket, in order this to be further investigated.

Be sure to include in the ticket the API Call, along with the Full API Response.

Best,

Krassimir

**Comment by pjenei** [comment]
Hi,

I had the same issue using C#. Downgrading Newtonsoft.Json to 9.0.1 in my Azure Functions project solved it. Mailjet.api v1.0.1 does not work with Newtonsoft.Json v10.x or v11.x.

Regards,
Peter Jenei

**Comment by Thoradin89** [comment]
Hello @vovikdrg,

We're in the process of updating the whole documentation on the wiki. This will be addressed.
Meanwhile, the issue will be closed.

Regards,
T.
