### ISSUE TITLE
Method : get /template - VBS

### ISSUE THREAD

**Issue by GenoudJeremy** [mailjet/mailjet-apiv3-dotnet#33]
When I use the same Api Key & secret key in the get method /template and get method /contactlist : 
- contactlist : works http_status = 200 
- template : doesn't work http_status = 401 "Unauthorized"

The only difference between this 2 request (in my code) is "/contactlist?All=True&Limit=100&Sort=Name" -> "/template"

`﻿

<% id_page = 4400 %>

<%
	id_template = trim(request.Form("id_list"))

	Dim rsGETMAILJET
	strSQL = "SELECT IS_MAILJET, IP_SMTP, MAILJET_USERNAME, MAILJET_PASSWORD FROM T_APPLICATION WHERE ID_APPLICATION = 2;"
	Set rsGETMAILJET = Server.CreateObject("ADODB.RecordSet")
	Set RetrieveData = rsGETMAILJET
	rsGETMAILJET.Open strSQL, dcnDB, 3, 3

	Set HttpReq = Server.CreateObject("MSXML2.ServerXMLHTTP")
	HttpReq.open "GET", "https://api.mailjet.com/v3/REST/template", False, trim(rsGETMAILJET("MAILJET_USERNAME")) , trim(rsGETMAILJET("MAILJET_PASSWORD"))
	HttpReq.setRequestHeader "Content-Type", "application/json"
	HttpReq.send

	if 200 <> HttpReq.status then
		dcnDB.execute("INSERT INTO T_ERREUR ( DESCRIPTION, URL, FONCTION, INFOS, USER_ID, HORODATAGE, TRAITE, USER_AGENT ) SELECT '"&NoTagUTF8(HttpReq.ResponseText)&"', '"&NoTagUTF8(Request.ServerVariables("HTTP_REFERER"))&"' , 'https://api.mailjet.com/v3/REST/template' , '"&HttpReq.status&"', "&Cdbl(Session("LoggedIn"))&", GETDATE(), 0, '"&get_user_agent()&"';")
		Response.Write -2
		Response.End()
    end if

	Set oJSON = New aspJSON

	oJSON.loadJSON(HttpReq.ResponseText)
%>

<select id="template" name="template" class="input_obligatoire form-control" onchange="/*affiche_templateslist_info();*/">
    <option value="">Select a template</option>
    <%
	if oJSON.data("Count") > 0 then
		For Each id In oJSON.data("Data")
			Set this = oJSON.data("Data").item(id)
			id_mailjet = oJSON.data("Data").item(id).item("ID")
			selected = ""
			if id_template = id_mailjet then
				selected = "selected=""selected"""
			end if
    %>
        <option value="<%=id_mailjet%>" <%=selected%>>
		<%=oJSON.data("Data").item(id).item("Name")%>
        </option>
    <%
      	Next
	end if
    %>
</select>
<% rsGETMAILJET.Close : Set rsGETMAILJET = Nothing %>
`

**Comment by abambova** [comment]
Hello @GenoudJeremy ,

We reviewed the information you provided above. It seems that you are not using our wrappers but you are using some of our API calls directly from VBS. We confirm that the requests you mentioned in Postman(for ex,) work correctly, so most probably the problem came from the way you configured the VBS. Is there a way that you are using the Dotnet wrappers directly? Looking forward to your reply!

**Comment by GenoudJeremy** [comment]
Hello @abambova 

We don't use Dotnet but ASP Classic.

**Comment by GenoudJeremy** [comment]
Could the problem come from 'Set HttpReq = Server.CreateObject("MSXML2.ServerXMLHTTP")' ?

**Comment by GenoudJeremy** [comment]
By going directly to the link via my browser, at first I am blocked but if I first switch to another link (like https://api.mailjet.com/v3/REST/apikey) and return to the link (https://api.mailjet.com/v3/REST/template) ... it works.

Moreover, the first link ask me the username and password but not the second link.

**Comment by goacoustic** [comment]
@GenoudJeremy Hi, I verified both routes and they works fine right now. 
The behavior is the same - both contactlist and template routes require basic auth with your API key and API secret key.

> By going directly to the link via my browser, at first I am blocked but if I first switch to another link (like https://api.mailjet.com/v3/REST/apikey) and return to the link (https://api.mailjet.com/v3/REST/template) ... it works.

This is expected behavior. The first URI returns **WWW-Authenticate** header that instructs the browser to use Basic auth. The browser shows a popup to request a username and password and then uses this username:password pair to authenticate requests to the MailJet API.

going to close this as a bit outdated, if you have any other requests - please, open the new issue.
