### ISSUE TITLE
Mailjet convert URLs in email body 

### ISSUE THREAD

**Issue by acidfreako** [mailjet/mailjet-apiv3-dotnet#73]
Hi Mailjet Support,

The below issue was previously raised in mailjet support ticket 1622083 with mailjet staff Anton. I was referred to this area to raise this issue. Please check the attachments in the support ticket as there are screenshots that are meant to be kept for privacy purpose.

We are experiencing an issue where the email html body https URL link has been encoded into a long gibberish URL without https. See mail jet request.png , html link encoded into a gibberish long URL with no https.png and Alloc8 Australia Mail - Downloaded Invoices.pdf .

This has caused an issue where users using a web based mail client such as Gmail tried to click the URL on chrome browser to download the file and are not able to do so. The reason for that is chrome security feature that disallow users to click on http link(non secure) to download file while on https protocol in the browser.

We have checked to see if the library of Mailjet client Post method was causing the issue but it is not. Can the support let us know how we can solve this issue ?

On another note, after upgrading to nuget 2.0.1 I have tried to fllow v3.1 documentation c# sample codehttps://dev.mailjet.com/email/guides/send-api-v31/#send-a-basic-email , it does not work. I have to use v3.0 documentation c# sample code, https://dev.mailjet.com/email/guides/send-api-V3/#send-a-basic-email .

**Comment by goacoustic** [comment]
Hi @acidfreako,

this is repo only for C# wrapper code, and wrapper does not contain code that can do such with links in your email body, so it's for sure not related to this repo.

From the problem description, I can guess that something is corrupting links in email. My best guess that this is related to the recipient mail server configuration rather than Mailjet. Some mail servers have security addons that open email content and scan them for viruses. Also they can replace attachments/links with it's own links to prevent opening malicious links or track link clicks.

Could you please try to repro this with other email recipient server, and then reopen the support ticket?
